server {
    listen 80;

    # Serve the Frontend Website
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Proxy API requests to the internal K8s Backend Service
    location /restaurants {
        proxy_pass http://backend-service:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}