apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: be-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 27017
        env:
        volumeMounts:
        - mountPath: "/data/db"
          name: pv-storage
      volumes:
        - name: pv-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
      tolerations:
      - key: "be-worker"
        operator: "Equal"
        value: "be-worker"
        effect: "NoSchedule"