apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: be-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: mohamed010/restaurant-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        envFrom:
          - secretRef:
              name: env-be
      tolerations:
      - key: "be-worker"
        operator: "Equal"
        value: "be-worker"
        effect: "NoSchedule"