apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: tariq126/backend-login
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        envFrom:
          - secretRef:
              name: env-be