apiVersion: v1
kind: Secret
metadata:
  name: env-be
type: Opaque
stringData:
  # We do NOT need AWS Keys here because Terraform attaches an IAM Role.
  AWS_REGION: "us-east-1"
  # This is the secret key used to sign user login tokens.
  JWT_SECRET: "h7Gj/8klM+n0bPq34/5sA9d12+XyZ/8vBqL9/1a2c3d4="