apiVersion: v1
kind: Secret
metadata:
  name: env-be
type: Opaque
stringData:
  # We do NOT need AWS Keys here because Terraform attaches an IAM Role.
  AWS_REGION: ${{ secrets.AWS_REGION }}
  # This is the secret key used to sign user login tokens.
  JWT_SECRET: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
