apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: tariq126/frontend-login
        imagePullPolicy: Always
        securityContext:
          runAsUser: 0
        ports:
        - containerPort: 80