name: CI/CD - Build & Terraform Deploy

on:
  push:
    branches: [ "test", "main" ]

env:
  # Map GitHub Secrets to Terraform Variables (TF_VAR_name)
  TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
  TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  # --- JOB 1: BUILD & PUSH DOCKER IMAGES ---
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Build Backend -> Matches image in k8s/backend/deploy.yml
      # CORRECTION: Changed mohamed010 -> tariq126 to match your Docker Hub
      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./application/backend
          file: ./application/backend/Dockerfile
          push: true
          tags: tariq126/backend-login:latest

      # Build Frontend -> Matches image in k8s/frontend/deploy.yml
      # CORRECTION: Changed mohamed010 -> tariq126
      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./application/frontend
          file: ./application/frontend/Dockerfile
          push: true
          tags: tariq126/frontend-login:latest

  # --- JOB 2: DEPLOY INFRASTRUCTURE (TERRAFORM) ---
  terraform-deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./application/terrafrom

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        # -auto-approve: Don't ask for confirmation
        # The variables are injected automatically via env: TF_VAR_...
        run: terraform apply -auto-approve

      - name: Upload SSH Key
        uses: actions/upload-artifact@v4
        with:
          name: ssh-key
          path: application/terrafrom/ssh-key.pem