name: CI/CD - Build, Push, and Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  # --- JOB 1: BUILD & PUSH ---
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # BACKEND (Path: application/backend)
      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./application/backend
          file: ./application/backend/Dockerfile
          push: true
          tags: mohamed010/restaurant-backend:latest

      # FRONTEND (Path: application/frontend)
      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./application/frontend
          file: ./application/frontend/Dockerfile
          push: true
          tags: mohamed010/restaurant-frontend:latest

  # --- JOB 2: DEPLOY TO EC2 ---
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # STEP 1: Copy the Kubernetes file to the server
      - name: Copy K8s file to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "application/k8s-deployment.yaml"
          target: "~/app"
          strip_components: 1

      # STEP 2: Apply changes on the server
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Apply the file we just copied
            sudo k3s kubectl apply -f ~/app/k8s-deployment.yaml
            
            # Restart deployments to pull new images
            sudo k3s kubectl rollout restart deployment/backend
            sudo k3s kubectl rollout restart deployment/frontend